PROFILE ?= rv32i
SUPPORTED_PROFILES := rv32i rv32izmmul rv32im

ifeq ($(filter $(PROFILE),$(SUPPORTED_PROFILES)),)
$(error Unsupported PROFILE=$(PROFILE). Supported profiles: $(SUPPORTED_PROFILES))
endif

ifeq ($(PROFILE),rv32i)
PROFILE_NAME := RV32I
PROFILE_MARCH := rv32i
PROFILE_SPIKE_ISA := RV32I
PROFILE_ACT4_CONFIG := bluerv32-rv32i
PROFILE_ACT4_EXTENSIONS := I
PROFILE_BSC_DEFINES :=
else ifeq ($(PROFILE),rv32izmmul)
PROFILE_NAME := RV32IZmmul
PROFILE_MARCH := rv32i_zmmul
PROFILE_SPIKE_ISA := RV32I_Zmmul
PROFILE_ACT4_CONFIG := bluerv32-rv32izmmul
PROFILE_ACT4_EXTENSIONS := I,Zmmul
PROFILE_BSC_DEFINES := -D RV32_ZMMUL
else ifeq ($(PROFILE),rv32im)
PROFILE_NAME := RV32IM
PROFILE_MARCH := rv32im
PROFILE_SPIKE_ISA := RV32IM
PROFILE_ACT4_CONFIG := bluerv32-rv32im
PROFILE_ACT4_EXTENSIONS := I,M
PROFILE_BSC_DEFINES := -D RV32_ZMMUL -D RV32_M
endif
